ALIAS = 'alias'
API = 'api'
CURRENCY = 'currency'
CURRENCY_CODE = 'currency_code'
DETAILS = 'details'
DIGITS = 'digits'
FLAG = 'flag'
NAME = 'name'
REGION = 'region'
SUBREDDIT = 'subreddit'
SUBREDDITS = 'subreddits'
SYSTEM = 'system'
WEBSITES = 'websites'
WISHLISTED = 'wishlisted'

ID = '_id'
GAME_ID = 'game_id'
TITLE = 'title'
TITLE_EN = 'title_en'
TITLE_JP = 'title_jp'
NSUIDS = 'nsuids'
CATEGORIES = 'categories'
NUMBER_OF_PLAYERS = 'number_of_players'
PUBLISHED_BY_NINTENDO = 'published_by_nintendo'
RELEASE_DATE = 'release_date'

SCORES = 'scores'
METASCORE = 'metascore'
USERSCORE = 'userscore'
LAST_UPDATE = 'last_update'
LATEST_SALE = 'latest_sale'

REDDIT = 'reddit'
SUBMISSION_ID = 'subsmission_id'
POST = 'post'
CREATED_AT = 'created_at'
UPDATED_AT = 'updated_at'
URL = 'url'
EXPIRES_AT = 'expires_at'

DISCOUNT = 'discount'
END_DATE = 'end_date'
FULL_PRICE = 'full_price'
SALE = 'sale'
SALES = 'sales'
SALE_PRICE = 'sale_price'
START_DATE = 'start_date'

DB = 'DB'

GAMES = 'games'

# Countries/ Regions
AU = 'AU'
CA = 'CA'
CH = 'CH'
ES = 'ES'
EU = 'EU'
GB = 'GB'
JP = 'JP'
MX = 'MX'
NA = 'NA'
NZ = 'NZ'
RU = 'RU'
SE = 'SE'
US = 'US'
ZA = 'ZA'


# Systems
N3DS = '3DS'
SWITCH = 'Switch'
